### ISSUE TITLE
Is it posslible to gather ns objects in Python?

### ISSUE THREAD

**Issue by cclauss** [jsbain/objc_hacks#1]
Could

``` python
elif isinstance(py_obj, list):   # line 481 of obj_c.py
    arr = NSMutableArray.array()
    for obj in py_obj:
    arr.addObject_(ns(obj))
    return arr
```

be rewritten as

``` python
elif isinstance(py_obj, list):   # line 481 of obj_c.py
    return NSMutableArray.array([ns(obj) for obj in py_obj])
```

If so, would it matter?

**Comment by jsbain** [comment]
does that work?  i dont think array() takes arguments.  im finding objc is very very explicit.  from https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSArray_Class/index.html#//apple_ref/occ/clm/NSArray/arrayWithObjects:  maybe `arrayWithObjects_`, perhaps expanding the tuple so it looks like multiple arguments.  actually, youd have to check if the list only has one object,in which case youd call `arrayWithObject_` instead!

**Comment by jsbain** [comment]
on second thought, that method takea a pointer to a list which ends with `nil`... not sure we can do that easily with ctypes.  maybe a python `array` of na objects.  as to whether it matters, i think maybe not.  i think the point of this code is to ensure you never have to worry about lists, because they are automatically converted to NSMutableArrays.

**Comment by cclauss** [comment]
Leave it as it is ;-)

**Comment by cclauss** [comment]
return NSMutableArray.arrayWithObjects([ns(obj) for obj in py_obj] + [None])  # ;-)
